name: Label Issues (Permissions Example)
on:
  issues:
    types:
      - opened
jobs:
  assign-label:
    runs-on: ubuntu-latest
    steps:
      - name : Output Information
        run : echo "github?  https://api.github.com/${{github.repository}}/issues/${{github.event.issue.number}}/labels"
      - name: Assign label
        if: contains(github.event.issue.title, 'bug')
        run: |
          curl -X POST -u ${{github.repository_owner}}:${{ secrets.GITHUB_TOKEN }} -d “{\”labels\”: [\"bug\"]}” https://api.github.com/${{github.repository}}/issues/${{github.event.issue.number}}/labels